# L05 - Data Preprocessing and Machine Learning with Scikit-Learn

- Instructor: Dalcimar Casanova (dalcimar@gmail.com)
- Course website: https://www.dalcimar.com/disciplinas/aprendizado-de-maquina
- Bibliography: based on lectures of Dr. Sebastian Raschka
- Course website: http://pages.stat.wisc.edu/~sraschka/teaching/

In [ ]:
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')


df = pd.read_csv('/content/drive/My Drive/Disciplinas/Aprendizado de Máquina/Public/L05_preprocessing-and-sklearn/code/data/iris.csv')
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Id  SepalLength[cm]  ...  PetalWidth[cm]      Species
0   1              5.1  ...             0.2  Iris-setosa
1   2              4.9  ...             0.2  Iris-setosa
2   3              4.7  ...             0.2  Iris-setosa
3   4              4.6  ...             0.2  Iris-setosa
4   5              5.0  ...             0.2  Iris-setosa

[5 rows x 6 columns]

In [ ]:
d = {'Iris-setosa': 0,
     'Iris-versicolor': 1,
     'Iris-virginica': 2}

df['Species'] = df['Species'].map(d)
df.head()

Id  SepalLength[cm]  ...  PetalWidth[cm]  Species
0   1              5.1  ...             0.2        0
1   2              4.9  ...             0.2        0
2   3              4.7  ...             0.2        0
3   4              4.6  ...             0.2        0
4   5              5.0  ...             0.2        0

[5 rows x 6 columns]

In [ ]:
X = df.iloc[:, 1:5].values
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
y = df['Species'].values
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=123, stratify=y)
np.bincount(y_train)

array([40, 40, 40])

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)
X_train_std = scaler.transform(X_train)
X_test_std = scaler.transform(X_test)
X_train_std

array([[-0.15385273, -0.58123819,  0.20169198,  0.14079576],
       [-1.03903283,  0.34874292, -1.46947014, -1.31116056],
       [ 0.60487307, -1.74371458,  0.37457082,  0.14079576],
       [-0.53321563,  1.97620986, -1.18133874, -1.0471685 ],
       [-0.53321563,  1.5112193 , -1.2965913 , -1.31116056],
       [ 2.37523326, -1.04622875,  1.81522782,  1.46075606],
       [-0.53321563,  0.81373347, -1.2965913 , -1.0471685 ],
       [-1.03903283,  1.27872403, -1.35421758, -1.31116056],
       [ 1.11069026,  0.58123819,  1.12371246,  1.196764  ],
       [ 1.49005316,  0.34874292,  0.54744966,  0.27279179],
       [-1.54485003,  0.81373347, -1.35421758, -1.17916453],
       [-0.91257853,  1.74371458, -1.06608618, -1.0471685 ],
       [-1.03903283,  0.81373347, -1.2965913 , -1.31116056],
       [ 1.74296176, -0.11624764,  1.18133874,  0.53678385],
       [-1.29194143,  0.81373347, -1.06608618, -1.31116056],
       [ 0.47841877,  0.81373347,  0.95083362,  1.46075606],
       [-1.16548713,  0.

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=3)

knn_model.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [ ]:
y_pred = knn_model.predict(X_test)
print(y_pred)
print(y_test)

[1 0 2 2 0 0 2 2 2 0 0 2 2 1 2 1 0 0 0 0 0 2 2 1 2 2 1 1 1 1]
[1 0 2 2 0 0 2 1 2 0 0 1 2 1 2 1 0 0 0 0 0 2 2 1 2 2 1 1 1 1]


In [ ]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.9333333333333333